#components:
#  securitySchemes:
#    BasicAuth:
#      type: http
#      scheme: basic
#    BearerAuth:
#      type: http
#      scheme: bearer
#
#
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 339978069723-ou36ab58gnn2bvd9frjae01f9c5p1akg.apps.googleusercontent.com
#            clientSecret: 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
#            scope:
#              - email
#              - profile
#              - openid
#        accessTokenUri: https://www.googleapis.com/oauth2/v3/token
#        userAuthorizationUri: https://www.google.com/o/oauth2/auth
#        tokenName: oauth_token
#        authenticationScheme: query
#        clientAuthenticationScheme: form
#
#        resource:
#         userInfoUri: https://www.googleapis.com/userinfo/v2/me
#         preferTokenInfo: false